Add basic order methods
ahivert/tgtg-python pull request #217
Opened 2023-02-19 10:19 UTC by Jurrie

- create_order(item_id, item_count)
- get_order_status(order_id)
- abort_order(order_id)

2023-02-19 10:21 UTC, Jurrie commented
This will only allow you to create orders, not to pay them. For this, you'll need additional methods.

2023-03-17 22:51 UTC, Leon-Sander commented
I tried the create_order method, and it reserved the bag for me. But it was not visible in the app, I could not pay since in the app is no state of reserved and not paid, only paid which then is reserved. Do you know how it is possible to pay at this point?

2023-03-19 14:40 UTC, Jurrie commented
Indeed; the app uses the create_order method to reserve a bag. After that, additional methods are invoked to pay for the order. These methods are different for every payment method. I only use one payment method, and didn't bother yet to dissect all those methods.

I thought I'd put these methods in PR first, and wait to see if these get merged. After that, and when I have time (and feel like it) I'll have a crack at the methods needed for payment of orders. But since my PR is stale for a month now, I doubt it will get merged any time soon.

But, after reserving the bag, did you check "my account" (I mean the bottom right button) → "Mag Bags & Parcels saved"? Maybe it's listed there? (I don't know for sure if it should be listed there, just guessing.)

2023-03-20 14:04 UTC, ahivert requested changes
Cool ! Thank you ! Sorry for the delay, just small remarks and this will be merged :)

2023-03-20 14:04 UTC, ahivert commented on README.md
> +In other words: you can create an order via this framework, but you can not pay for it.
```suggestion
In other words: you can create an order via this client, but you can not pay for it.
```

2023-03-20 17:30 UTC, Leon-Sander commented
> Indeed; the app uses the create_order method to reserve a bag. After that, additional methods are invoked to pay for the order. These methods are different for every payment method. I only use one payment method, and didn't bother yet to dissect all those methods.
> 
> I thought I'd put these methods in a PR first, and wait to see if these get merged. After that, and when I have time (and feel like it) I'll have a crack at the methods needed for payment of orders. But since my PR is stale for a month now, I doubt it will get merged any time soon.
> 
> But, after reserving the bag, did you check "my account" (I mean the bottom right button) → "Mag Bags & Parcels saved"? Maybe it's listed there? (I don't know for sure if it should be listed there, just guessing.)

I Just tried it and unfortunately they are not listed in the app. Do you have a payment method implemented for yourself and could share it? It would be amazing to be able to use it. Great work so far.

2023-03-20 19:21 UTC, Jurrie commented
> Do you have a payment method implemented for yourself and could share it? It would be amazing to be able to use it. Great work so far.

I do have a payment method implemented. But it's very rough code. I really should clean it up, add some safety checks, add some documentation, make it tidy 😀 I can't give any promises on when that will be done.

In the mean time, you could try to figure out the API calls for yourself. It would be a more long-term solution anyway. Please check [the reply I gave](https://github.com/ahivert/tgtg-python/issues/215#issuecomment-1476785324) on the question of solve-fx. I think intercepting app traffic is a nice skill to have, and not all that hard. Quite fun actually! 😀

2023-03-20 19:39 UTC, merged

2023-05-28 19:47 UTC, Vivalemuc commented
@Jurrie 

Can you share the minimalist snipet to pay an order ? Just to see the mechanism !

Thanks :)